# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Jeff Culverhouse
import asyncio
from argparse import Namespace
from asyncio import AbstractEventLoop
from collections.abc import Callable, Coroutine
from logging import Logger
from types import FrameType
from typing import Any, Protocol, TypeVar

from mqtt_helper import MqttHelper
from paho.mqtt.client import Client, ConnectFlags, DisconnectFlags, MQTTMessage
from paho.mqtt.properties import Properties
from paho.mqtt.reasoncodes import ReasonCode

from vision2mqtt.mixins.presence import PresenceTracker
from vision2mqtt.models.events import DetectedObject, MotionEvent, VisionResult

_T = TypeVar("_T")


class VisionServiceProtocol(Protocol):
    args: Namespace | None
    client_id: str
    config: dict[str, Any]
    ha_enabled: bool
    logger: Logger
    loop: AbstractEventLoop
    mqtt_config: dict[str, Any]
    mqtt_helper: MqttHelper
    mqttc: Client
    qos: int
    queue: asyncio.Queue[MotionEvent]
    running: bool
    seen_cameras: set[str]
    _camera_discovery_lock: asyncio.Lock
    service_name: str
    service: str
    vision_config: dict[str, Any]
    _detector_model: Any
    _axcl_input_name: str
    _axcl_input_size: int
    _axcl_nchw: bool
    _presence_tracker: PresenceTracker
    _axcl_smi_path: str | None

    def _probe_axcl_smi(self) -> str | None: ...
    @staticmethod
    def _read_cpu_temperature() -> float | None: ...
    def _collect_npu_stats(self) -> dict[str, float]: ...
    @staticmethod
    def _parse_axcl_smi_output(output: str) -> dict[str, float]: ...
    def collect_system_stats(self) -> dict[str, float]: ...
    def build_system_stats_components(self) -> dict[str, dict[str, Any]]: ...
    async def publish_system_stats(self) -> None: ...

    async def detect_objects(self, event: MotionEvent) -> VisionResult: ...
    async def heartbeat(self) -> None: ...
    async def init_detector(self) -> None: ...
    async def main_loop(self) -> None: ...
    async def mqtt_on_connect(
        self, client: Client, userdata: dict[str, Any], flags: ConnectFlags, reason_code: ReasonCode, properties: Properties | None
    ) -> None: ...
    async def mqtt_on_disconnect(
        self, client: Client, userdata: Any, flags: DisconnectFlags, reason_code: ReasonCode, properties: Properties | None
    ) -> None: ...
    async def mqtt_on_message(self, client: Client, userdata: Any, msg: MQTTMessage) -> None: ...
    async def mqtt_on_subscribe(self, client: Client, userdata: Any, mid: int, reason_code_list: list[ReasonCode], properties: Properties) -> None: ...
    async def mqtt_on_log(self, client: Client, userdata: Any, paho_log_level: int, msg: str) -> None: ...
    async def mqttc_create(self) -> None: ...
    async def publish_camera_discovery(self, camera_id: str, camera_name: str) -> None: ...
    async def publish_camera_state(self, camera_id: str, object_count: int, processing_time_ms: float) -> None: ...
    async def publish_service_discovery(self) -> None: ...
    async def publish_service_availability(self, status: str = "online") -> None: ...
    async def publish_service_state(self) -> None: ...
    async def publish_vision_result(self, event: MotionEvent, result: VisionResult) -> None: ...
    async def worker(self, worker_id: int) -> None: ...

    def _wrap_async(
        self,
        coro_func: Callable[..., Coroutine[Any, Any, _T]],
    ) -> Callable[..., None]: ...

    def compute_composites(self, result: VisionResult) -> dict[str, bool]: ...
    def get_simplified_label(self, raw_label: str) -> str | None: ...
    def _detect_axcl(self, image_b64: str) -> tuple[list[DetectedObject], str]: ...
    def _detect_ultralytics(self, image_b64: str) -> tuple[list[DetectedObject], str]: ...
    def _load_axcl_model(self, model_path: str) -> Any: ...
    def _load_ultralytics_model(self, model_path: str) -> Any: ...
    def handle_signal(self, signum: int, _: FrameType | None) -> Any: ...
    def heartbeat_ready(self) -> None: ...
    async def check_presence_cooldowns(self) -> None: ...
    def load_config(self, config_arg: Any | None) -> dict[str, Any]: ...
    def mark_ready(self) -> None: ...
    def read_file(self, file_name: str) -> str: ...
    def _read_version_file(self) -> str: ...
    def _get_camera_min_confidence(self, camera_id: str, label: str) -> float: ...
    def _get_camera_default_label(self, camera_id: str) -> str | None: ...
    def _get_camera_mode(self, camera_id: str) -> str: ...
